# Goreleaser configuration for mongo-scaffold
# Builds and releases m and mlaunch binaries

project_name: mongo-scaffold

version: 2
# Build configuration
builds:
  - id: m
    main: ./cmd/m
    binary: m
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: mlaunch
    main: ./cmd/mlaunch
    binary: mlaunch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: mongo-cluster
    main: ./cmd/mongo-cluster
    binary: mongo-cluster
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
    builds:
      - m
      - mlaunch
      - mongo-cluster

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Snapshots
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew configuration
homebrew:
  - name: mongo-scaffold
    tap:
      owner: zph
      name: mongo-scaffold
    homepage: "https://github.com/zph/mongo-scaffold"
    description: "MongoDB version manager and cluster launcher"
    license: "MIT"
    binaries:
      - m
      - mlaunch
      - mongo-cluster
    # Test block for homebrew formula
    test: |
      system "#{bin}/m", "--version"
      system "#{bin}/mlaunch", "--help"
      system "#{bin}/mongo-cluster", "--help"

# GitHub release configuration
release:
  github:
    owner: zph
    name: mongo-scaffold
  # Draft releases
  draft: false
  # Prerelease for tags with -alpha, -beta, -rc
  mode: replace
  header: |
    ## {{ .Tag }}

    {{ if .PreviousTag }}
    **Full Changelog**: https://github.com/zph/mongo-scaffold/compare/{{ .PreviousTag }}...{{ .Tag }}
    {{ end }}

# Docker (optional - can be removed if not needed)
# dockers:
#   - goos: linux
#     goarch: amd64
#     image_templates:
#       - "ghcr.io/zph/mongo-scaffold:{{ .Tag }}"
#       - "ghcr.io/zph/mongo-scaffold:latest"
#     dockerfile: Dockerfile

# NFPM (for .deb and .rpm packages - optional)
# nfpms:
#   - id: default
#     package_name: mongo-scaffold
#     file_name_template: "{{ .ConventionalFileName }}"
#     maintainer: "zph <zph@example.com>"
#     description: "MongoDB version manager and cluster launcher"
#     license: "MIT"
#     formats:
#       - deb
#       - rpm
#     dependencies:
#       - mongodb-community
#     contents:
#       - src: "{{ .ArtifactPath }}"
#         dst: "/usr/local/bin/{{ .Binary }}"
#         file_info:
#           mode: 0755

# Before hook (optional)
# before:
#   hooks:
#     - go mod download
#     - go generate ./...

# After hook (optional)
# after:
#   hooks:
#     - echo "Release {{ .Tag }} completed!"

