# Goreleaser configuration for mongo-scaffold
# Builds and releases m and mlaunch binaries

project_name: mongo-scaffold

version: 2
# Build configuration
builds:
  - id: m
    main: ./cmd/m
    binary: m
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: mlaunch
    main: ./cmd/mlaunch
    binary: mlaunch
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: mongo-cluster
    main: ./cmd/mongo-cluster
    binary: mongo-cluster
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
# Create separate archives for each build to support homebrew_casks
# Note: builds field is deprecated but still functional - needed to specify which builds go into each archive
archives:
  - id: m
    builds:
      - m
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
  - id: mlaunch
    builds:
      - mlaunch
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
  - id: mongo-cluster
    builds:
      - mongo-cluster
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*

# Checksums
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Snapshots
# Note: snapshot.name_template is deprecated in GoReleaser 2.5.0
# Removed to avoid deprecation warnings
snapshot: {}

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew Casks configuration
homebrew_casks:
  - name: mongo-scaffold
    repository:
      owner: zph
      name: mongo-scaffold
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Casks
    homepage: "https://github.com/zph/mongo-scaffold"
    description: "MongoDB version manager and cluster launcher"
    license: "MIT"
    url:
      verified: github.com/zph/mongo-scaffold
    ids:
      - m
      - mlaunch
      - mongo-cluster
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/m"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mlaunch"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongo-cluster"]
          end

# GitHub release configuration
release:
  github:
    owner: zph
    name: mongo-scaffold
  # Draft releases
  draft: false
  # Prerelease for tags with -alpha, -beta, -rc
  mode: replace
  header: |
    ## {{ .Tag }}

    {{ if .PreviousTag }}
    **Full Changelog**: https://github.com/zph/mongo-scaffold/compare/{{ .PreviousTag }}...{{ .Tag }}
    {{ end }}

# Docker (optional - can be removed if not needed)
# dockers:
#   - goos: linux
#     goarch: amd64
#     image_templates:
#       - "ghcr.io/zph/mongo-scaffold:{{ .Tag }}"
#       - "ghcr.io/zph/mongo-scaffold:latest"
#     dockerfile: Dockerfile

# NFPM (for .deb and .rpm packages - optional)
# nfpms:
#   - id: default
#     package_name: mongo-scaffold
#     file_name_template: "{{ .ConventionalFileName }}"
#     maintainer: "zph <zph@example.com>"
#     description: "MongoDB version manager and cluster launcher"
#     license: "MIT"
#     formats:
#       - deb
#       - rpm
#     dependencies:
#       - mongodb-community
#     contents:
#       - src: "{{ .ArtifactPath }}"
#         dst: "/usr/local/bin/{{ .Binary }}"
#         file_info:
#           mode: 0755

# Before hook (optional)
# before:
#   hooks:
#     - go mod download
#     - go generate ./...

# After hook (optional)
# after:
#   hooks:
#     - echo "Release {{ .Tag }} completed!"

