# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoScaffold < Formula
  desc "MongoDB version manager and cluster launcher"
  homepage "https://github.com/zph/mongo-scaffold"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zph/mongo-scaffold/releases/download/v0.9.1/mongo-scaffold_darwin_amd64.tar.gz"
      sha256 "95364cdd2320096bcce7f3a9e9e1653227ffe7ca9a426cbeab4760a397457a11"

      def install
        bin.install "m"
        bin.install "mlaunch"
        bin.install "mongo-cluster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zph/mongo-scaffold/releases/download/v0.9.1/mongo-scaffold_darwin_arm64.tar.gz"
      sha256 "7fe6b7519d52541886b011015708f002284a852f8ed8e88d336a07ac3bdf5073"

      def install
        bin.install "m"
        bin.install "mlaunch"
        bin.install "mongo-cluster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zph/mongo-scaffold/releases/download/v0.9.1/mongo-scaffold_linux_amd64.tar.gz"
        sha256 "ff7dc3505903af5e9bbb3ac56e23f5aec7aef962a93336f008d14ee96e9f105c"

        def install
          bin.install "m"
          bin.install "mlaunch"
          bin.install "mongo-cluster"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zph/mongo-scaffold/releases/download/v0.9.1/mongo-scaffold_linux_arm64.tar.gz"
        sha256 "473e308df8f956bb0baa059e3a1a2bf0bdaf41444584be1959265937b988f770"

        def install
          bin.install "m"
          bin.install "mlaunch"
          bin.install "mongo-cluster"
        end
      end
    end
  end

  test do
    system "#{bin}/m", "--version"
    system "#{bin}/mlaunch", "--help"
    system "#{bin}/mongo-cluster", "--help"
  end
end
