# This file was generated by GoReleaser. DO NOT EDIT.
cask "mongo-scaffold" do
  name "mongo-scaffold"
  desc "MongoDB version manager and cluster launcher"
  homepage "https://github.com/zph/mongo-scaffold"
  version "0.9.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m"
  binary "mlaunch"
  binary "mongo-cluster"

  on_macos do
    on_intel do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_darwin_amd64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "02cc7c5603a08d905f0f9fcd68892845807480387ab70bf92018fa8e99d12544"
    end
    on_arm do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_darwin_arm64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "98894d49b4e11d4ab044d7c48a2f185cd6c38f4076a43c760238f63386eda19b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_linux_amd64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "b4f668fda41d169b1219cc8ba5b244cfcb70ccca079e0f899c2df1e02dbc96fd"
    end
    on_arm do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_linux_arm64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "c32649605532c9bfdcf6cc57a7698abd6010d489df22800d06a61e6709c7de5a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/m"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mlaunch"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongo-cluster"]
    end
  end

  # No zap stanza required
end
