# This file was generated by GoReleaser. DO NOT EDIT.
cask "mongo-scaffold" do
  name "mongo-scaffold"
  desc "MongoDB version manager and cluster launcher"
  homepage "https://github.com/zph/mongo-scaffold"
  version "0.9.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "m"
  binary "mlaunch"
  binary "mongo-cluster"

  on_macos do
    on_intel do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_darwin_amd64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "8371c43d42bed114379a12ba5ba85d41effc320fd1d86e6f60c3d167c0d1e00a"
    end
    on_arm do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_darwin_arm64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "9eca7616693f58b79ca94d880286e0c3b26a8913f9081ef84d32ef733297e7c6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_linux_amd64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "ad86f85c76803ccc565d9ae8d59c5518a0d0e28201bce970b85f930a41677b3a"
    end
    on_arm do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_linux_arm64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "311333d7bda07ecb3c071d77fa073df6af0fdf4557563a8bfe82216951ca5020"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/m"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mlaunch"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongo-cluster"]
    end
  end

  # No zap stanza required
end
