# This file was generated by GoReleaser. DO NOT EDIT.
cask "mongo-scaffold" do
  name "mongo-scaffold"
  desc "MongoDB version manager and cluster launcher"
  homepage "https://github.com/zph/mongo-scaffold"
  version "0.9.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mongo-scaffold"

  on_macos do
    on_intel do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_darwin_amd64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "a5810fb5b1ec97fc7705cfabcff1b566b1891c20fff9cca590f40277f48b8d84"
    end
    on_arm do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_darwin_arm64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "8dd51c9b5d9683fb70357f1406ffe95e110e4c11739dfea61d7e7e784ebad5c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_linux_amd64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "3b5c51efb004ecd92063d81d2aaa657bf34c3a9cf2e3fc4385e591c58a4fd06c"
    end
    on_arm do
      url "https://github.com/zph/mongo-scaffold/releases/download/v#{version}/mongo-scaffold_linux_arm64.tar.gz",
        verified: "github.com/zph/mongo-scaffold"
      sha256 "0e6d823dffb96ba028448143e67237b15dd421de7dfea6b6553039c607c09ea1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/m"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mlaunch"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongo-cluster"]
    end
  end

  # No zap stanza required
end
